In [ ]:
#Print numpy version
np.__version__

'1.19.5'

In [ ]:
#To reverse an array
arr1 = np.array([1,2,3,4,5,6,7,])
arr1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
#Convert list and tuples into array
l = [100,90,40,700,200,10]
arr_lst = np.array(l)
print(arr_lst)

t = (10,11,12,100,50,70)
arr_tuple = np.array(t)
print(arr_tuple)

[100  90  40 700 200  10]
[ 10  11  12 100  50  70]


In [ ]:
#Python Program to find common elements in two array
import numpy as np
arr1 = np.array([3,4,5, 10, 11, 0])
arr2 = np.array([2,8,0, 1,100,20,11,55])
shape_of_array = arr2.shape[0] if arr1.shape[0] > arr2.shape[0] else arr1.shape[0]
arr3 = [arr1[i] for i in range(arr1.shape[0]) if arr1[i] in arr2]
arr3

[11, 0]

In [ ]:
#Python Program to compare two arrays.
#All method doesnt work if sizes are not equal
import numpy as np
arr1 = np.array([3,4,5, 10, 11, 0])
arr2 = np.array([2,8,0, 1,100,20,11,55])
arr1 == arr2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


False

In [ ]:
#Write a Python program to change the dimension of an array.
arr3 = np.array([1,2,3,4,5,10])
s = arr3.shape[0]
sizes_list = [(i, int(s/i)) for i in range(1,s+1) if s%i == 0]
for i in range(len(sizes_list)):
  arr3 = arr3.reshape(sizes_list[i][0], sizes_list[i][1])
  print(arr3.shape)

(1, 6)
(2, 3)
(3, 2)
(6, 1)


In [ ]:
#Python Program to sum all the multiples of 3, 5 upto 10
import numpy as np
arr1 = np.array([i for i in range(3,100) if i % 3 == 0 or i % 5 == 0])
arr1.sum()

2318

In [ ]:
#Write a Python program to convert a NumPy array into Python list structure.
arr = np.array([10,20,0,50,30,11])
converted_lst = list(arr)
type(converted_lst)

list

In [ ]:
#Write a Python program to how to add an extra column to a numpy array.
arr1 = np.array([[10,20,40], [20,40,10], [40,10,20]])
arr2 = np.array([[100],[300],[500]])
arr2 = np.array([[300,500,800]])
np.concatenate((arr1,arr2.reshape(1,3)))

array([[ 10,  20,  40],
       [ 20,  40,  10],
       [ 40,  10,  20],
       [300, 500, 800]])

In [ ]:
#Write a Python program to check whether the numpy array is empty or not
a = np.array([])
b = np.array([[10,20,30],[40,50,60]])
c=np.array([10,20,30])
if a.size is 0:
   print("Array is empty")
   

Array is empty


In [ ]:
#Normalise a 3*3 random matrix
arr1 = np.random.rand(2,2)
print("Before Normalisation: ")
print(arr1)
xmax, xmin = arr1.max(), arr1.min()
x = (arr1 - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Before Normalisation: 
[[0.18645822 0.80758027]
 [0.74707947 0.67484735]]
After normalization:
[[0.         1.        ]
 [0.90259435 0.78630138]]


In [ ]:
# How to ignore all numpy warnings (not recommended)?
a=np.arange(12).reshape(3,4)

arr1 = np.array([3,4,5, 10, 11])
arr2 = np.array([2,8,0, 1,100,20])
x = np.array([1,2,3,4])
print('Before ignoring all warning')
np.seterr(all='warn')
print(np.geterr())
print(np.divide(x, 0))


Before ignoring all warning
{'divide': 'warn', 'over': 'warn', 'under': 'warn', 'invalid': 'warn'}
[inf inf inf inf]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


In [ ]:
print('After ignoring all warning')
np.seterr(all='ignore')
print(np.geterr())
print(np.divide(x, 0))

After ignoring all warning
{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
[inf inf inf inf]


In [ ]:
#swap two array
a = np.arange(25).reshape(5,5)
#Before Swaping
print(a)
b = a[:1].copy()
a[:1] = a[1:2]
a[1:2] = b
#After Swapping
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#Python program to create a random vector of size 10 and sort it.
s = np.random.rand(10)
s.sort()
s

array([0.07925702, 0.09333225, 0.23615802, 0.29252677, 0.48595423,
       0.6290336 , 0.63403794, 0.73461511, 0.88432014, 0.9584722 ])

In [ ]:
#Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, 
#compute the mean of each sample, and then compute percentiles over the means).
original_array = np.array([1,2,3,4,5,6])
N = 20
i=0
while i <= N :
      x = np.random.choice(original_array, original_array.size, replace=True)
      y = np.mean(x)
      p = np.percentile(x,y)
      print(p)
      i=i+1


1.175
1.0
1.1833333333333333
1.0
1.175
1.0
3.0000000000000004
1.0
1.15
1.1
1.3333333333333335
2.2083333333333335
4.241666666666666
1.4000000000000001
1.1916666666666667
1.0
1.3666666666666667
1.0
3.0
2.166666666666667
2.0


In [ ]:
#Program to compare two random array are equal or not
s = np.random.rand(10)
p = np.random.rand(10)
s==p

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
#with 1-D
s=np.array([3,1,2])
p=np.array([5,4,2])

print(np.add(s,p))
print(np.subtract(s,p))
print(np.multiply(s,p))
print(np.divide(s,p))

#with 2-D
#Addition of two matrices
s = np.arange(12).reshape(12,1)
p = np.arange(24).reshape(12,2)
np.add(s,p)
#Subtarction of two matrices element_wise
np.subtract(s,p)
#Multiplication of two matrices element_wise
np.dot(s.reshape(1,12) ,p)
#Divide two matrices element_wise
np.divide(s,p)


[8 5 4]
[-2 -3  0]
[15  4  4]
[0.6  0.25 1.  ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in true_divide


array([[       nan, 0.        ],
       [0.5       , 0.33333333],
       [0.5       , 0.4       ],
       [0.5       , 0.42857143],
       [0.5       , 0.44444444],
       [0.5       , 0.45454545],
       [0.5       , 0.46153846],
       [0.5       , 0.46666667],
       [0.5       , 0.47058824],
       [0.5       , 0.47368421],
       [0.5       , 0.47619048],
       [0.5       , 0.47826087]])

In [ ]:
#Write a Python program to get the dates of yesterday, today and tomorrow.
import datetime
#Yesterday
yesterday = np.datetime64('today') - 1
print(yesterday)
#Today
today = np.datetime64('today')
print(today)
#Tomorrow
tomorrow = np.datetime64('today') + 1
print(tomorrow)


2022-02-04
2022-02-05
2022-02-06
